#include <Python.h>
#include <glib.h>

#define PYINK_MODULE "pyink"
#define PYINK_START_FUNC "pyink_start"

typedef struct {
    PyObject_HEAD
} pybind_SPDesktopObject;

extern "C" void initpybInkscape(void);

namespace Inkscape {
namespace PyBind {

int
init(void) {
    PyObject *pyink;
    PyObject *pyink_start_func;
    PyObject *pyink_start_result;
    
    Py_Initialize();

    /*
     * This is the function generated by Cython for pybInkscape.pyx
     * module.
     */
    initpybInkscape();

    pyink = PyImport_ImportModule(PYINK_MODULE);
    if(pyink == NULL) {
	PyErr_Print();
	g_warning(PYINK_MODULE ": cannot be loaded");
	return -1;
    }
    pyink_start_func = PyObject_GetAttrString(pyink, PYINK_START_FUNC);
    if(pyink_start_func == NULL || !PyCallable_Check(pyink_start_func)) {
	g_warning(PYINK_START_FUNC ": is not a callable");
	return  -1;
    }

    pyink_start_result = PyObject_CallObject(pyink_start_func, NULL);
    if(pyink_start_result == NULL) {
	PyErr_Print();
	return -1;
    }

    return 0;
}

int
final(void) {
    Py_Finalize();
    return 0;
}

} // namespace PyBind
} // namespace Inkscape

/*
  Local Variables:
  mode:c++
  c-file-style:"stroustrup"
  c-file-offsets:((innamespace . 0)(inline-open . 0)(case-label . +))
  indent-tabs-mode:nil
  fill-column:99
  End:
*/
// vim: filetype=cpp:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:encoding=utf-8:textwidth=99 :
