###########################################################################
#  $Id$
###########################################################################
# Makefile for building with MinGW
###########################################################################

include ../../Makefile.mingw.common




OBJ = \
arikkei-dict.o arikkei-token.o

all: $(OBJ)

.cpp.o:
	$(CXX) $(CFLAGS) $(INC) -c -o $@ $<

.c.o:
	$(CXX) $(CFLAGS) $(INC) -c -o $@ $<


clean:
	$(RM) *.o
	$(RM) *.a
