/**
 * Python Interpreter wrapper for Inkscape
 *
 * Authors:
 *   Bob Jamison <rjamison@titan.com>
 *
 * Copyright (C) 2004 Inkscape.org
 *
 * Released under GNU GPL, read the file 'COPYING' for more information
 */


#include "InkscapePython.h"

#include <Python.h>

#include <stdio.h>

#include "inkscape_py.py.h"


/*
 * Generated by SWIG
 */
extern "C" void init_inkscape_py(void);


namespace Inkscape
{
namespace Extension
{
namespace Script
{

/*
 *
 */
InkscapePython::InkscapePython()
{
}

    

/*
 *
 */
InkscapePython::~InkscapePython()
{

}

    
    

/*
 *  Interpret an in-memory string
 */
bool InkscapePython::interpretScript(char *codeStr)
{
    Py_Initialize();
    init_inkscape_py();
    PyRun_SimpleString(inkscape_module_script);
    PyRun_SimpleString("inkscape = _inkscape_py.getInkscape()\n");
    PyRun_SimpleString(codeStr);
    Py_Finalize();
}

    
    

/*
 *  Interpret a named file
 */
bool InkscapePython::interpretFile(char *fileName)
{
    Py_Initialize();
    init_inkscape_py();
    PyRun_SimpleString(inkscape_module_script);
    PyRun_SimpleString("inkscape = _inkscape_py.getInkscape()\n");
    FILE *f = fopen(fileName, "r");
    PyRun_SimpleFile(f, fileName);
    fclose(f);
    Py_Finalize();

}



}  // namespace Script
}  // namespace Extension
}  // namespace Inkscape

//#########################################################################
//# E N D    O F    F I L E
//#########################################################################
