/**
 * Python Interpreter wrapper for Inkscape
 *
 * Authors:
 *   Bob Jamison <rjamison@titan.com>
 *
 * Copyright (C) 2004 Inkscape.org
 *
 * Released under GNU GPL, read the file 'COPYING' for more information
 */


#include "InkscapePython.h"

#include <Python.h>

#include <stdio.h>

#include "inkscape_py.py.h"


/*
 * Generated by SWIG
 */
extern "C" void init_inkscape_py(void);


namespace Inkscape {
namespace Extension {
namespace Script {

/*
 *
 */
InkscapePython::InkscapePython()
{
}

    

/*
 *
 */
InkscapePython::~InkscapePython()
{

}

    
    
static bool initialized = false;
/*
 *  Interpret an in-memory string
 */
bool InkscapePython::interpretScript(char *codeStr)
{
    if (!initialized)
        {
        Py_Initialize();
        init_inkscape_py();
        initialized = true;
        }
    PyRun_SimpleString(inkscape_module_script);
    PyRun_SimpleString("inkscape = _inkscape_py.getInkscape()\n");
    PyRun_SimpleString(codeStr);
    //Py_Finalize();
    return true;
}

    
    

/*
 *  Interpret a named file
 */
bool InkscapePython::interpretFile(char *fileName)
{
    if (!initialized)
        {
        Py_Initialize();
        init_inkscape_py();
        initialized = true;
        }
    PyRun_SimpleString(inkscape_module_script);
    PyRun_SimpleString("inkscape = _inkscape_py.getInkscape()\n");
    FILE *f = fopen(fileName, "r");
    PyRun_SimpleFile(f, fileName);
    fclose(f);
    //Py_Finalize();
    return true;
}



}  // namespace Script
}  // namespace Extension
}  // namespace Inkscape

/*
  Local Variables:
  mode:c++
  c-file-style:"stroustrup"
  c-file-offsets:((innamespace . 0)(inline-open . 0)(case-label . +))
  indent-tabs-mode:nil
  fill-column:99
  End:
*/
// vim: filetype=cpp:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:encoding=utf-8:textwidth=99 :
