

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "InkscapePerl.h"

#include <stdio.h>

#include "inkscape_perl.pm.h"

/*
 * Generated by SWIG
 */
extern "C" void boot_inkscape_perl(void);



/*
 *
 */
InkscapePerl::InkscapePerl()
{
}

    

/*
 *
 */
InkscapePerl::~InkscapePerl()
{

}

    
    

int
InkscapePerlParseBuf(char *startupCodeBuf, char *codeBuf);

bool InkscapePerl::interpretString(char *codeBuf)
{
    int ret = InkscapePerlParseBuf(inkscape_module_script, codeBuf);
    if (!ret)
        {
        return false;
        }
    return true;
}
    

/*
 *  Interpret a named file
 */
bool InkscapePerl::interpretFile(char *fileName)
{    
    
    return true;
}

