###########################################################################
#  $Id$
###########################################################################
# Makefile for building with MinGW
###########################################################################

include ../../Makefile.mingw.common



OBJ = \
repr-action.o repr-css.o repr-io.o repr.o repr-util.o

all: $(OBJ)


clean:
	$(RM) *.o
	$(RM) *.a
