<?xml version="1.0" encoding="utf-8"?> 

<xsl:stylesheet
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:k="http://www.inkscape.org/namespaces/keys"
   xmlns:h="http://www.w3.org/1999/xhtml"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   exclude-result-prefixes="k"
>

<xsl:output method="xml" encoding="utf-8" indent="no"/>

<xsl:variable name="style-section" select="'fill:black;fill-opacity:1;stroke:none;font-family:Bitstream Vera Sans;font-style:normal;font-weight:bold;font-size:24;text-anchor:start;writing-mode:lr;letter-spacing:-2;'"/>
<xsl:variable name="space-section" select="28"/>
<xsl:variable name="skip-section-title" select="21"/>
<xsl:variable name="skip-section-content" select="25"/>

<xsl:variable name="space-group" select="3"/>
<xsl:variable name="skip-group-content" select="1.5"/>

<xsl:variable name="style-title" select="'fill:black;fill-opacity:1;stroke:none;font-family:Bitstream Vera Sans;font-style:italic;font-weight:bold;font-size:7.4;text-anchor:start;writing-mode:lr;letter-spacing:-0.2;'"/>
<xsl:variable name="space-title" select="7"/>
<xsl:variable name="skip-title-content" select="5"/>

<xsl:variable name="space-keys" select="8"/>
<xsl:variable name="skip-keys-content" select="1"/>
<xsl:variable name="skip-keys-action" select="5"/> <!-- from keys-content -->

<xsl:variable name="space-mouse" select="11.5"/>
<xsl:variable name="skip-mouse-content" select="1.5"/>
<xsl:variable name="skip-mouse-action" select="5"/> <!-- from mouse-content -->

<xsl:variable name="style-note" select="'fill:black;fill-opacity:1;stroke:none;font-family:Bitstream Vera Sans;font-style:normal;font-weight:normal;font-size:3;text-anchor:start;writing-mode:lr;letter-spacing:0;'"/>
<xsl:variable name="space-note" select="4"/>
<xsl:variable name="skip-note-content" select="3"/>

<xsl:variable name="style-letterkey" select="'fill:black;fill-opacity:1;stroke:none;font-family:Bitstream Vera Sans;font-style:normal;font-weight:normal;font-size:4.4;text-anchor:start;writing-mode:lr;'"/>
<xsl:variable name="style-keyf" select="'fill:black;fill-opacity:1;stroke:none;font-family:Bitstream Vera Sans;font-style:normal;font-weight:normal;font-size:3.3;text-anchor:start;writing-mode:lr;letter-spacing:-0.4;'"/>
<xsl:variable name="style-keymisc" select="'fill:black;fill-opacity:1;stroke:none;font-family:Bitstream Vera Sans;font-style:normal;font-weight:normal;font-size:3.4;text-anchor:start;writing-mode:lr;letter-spacing:-0.2;'"/>
<xsl:variable name="style-action" select="'fill:black;fill-opacity:1;stroke:none;font-family:Bitstream Vera Sans;font-style:normal;font-weight:normal;font-size:6.4;text-anchor:start;writing-mode:lr;letter-spacing:-0.4;'"/>

<xsl:variable name="section-width" select="215"/>
<xsl:variable name="section-hskip" select="12"/>
<xsl:variable name="note-hskip" select="6"/>

<xsl:variable name="action-hskip" select="3"/>

<xsl:variable name="w-shift" select="15.46"/>
<xsl:variable name="w-ctrl" select="12.38"/>
<xsl:variable name="w-alt" select="10.67"/>
<xsl:variable name="w-left" select="8.7"/>
<xsl:variable name="w-right" select="10.9"/>
<xsl:variable name="w-letterkey" select="8.00"/>
<xsl:variable name="w-misc-wide" select="17.46"/>
<xsl:variable name="w-misc" select="12.38"/>
<xsl:variable name="w-arrows" select="12.38"/>
<xsl:variable name="w-mouse" select="7.0"/>

<xsl:variable name="w-key" select="31"/>

<xsl:template match="k:root">
<xsl:comment>

Do not edit this file.
It is generated automatically from doc/keys.xml by doc/keys-svg.xsl.

</xsl:comment>
<svg
   version="1.0"
   x="0"
   y="0"
   width="744.094482"
   height="1052.36218"
   id="svg559"
   sodipodi:version="0.32"
   inkscape:version="0.37cvs"
   sodipodi:docname="keys-sample.svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   sodipodi:docbase="/home/d/ink/inkscape">
  <sodipodi:namedview
     id="base"
     inkscape:zoom="0.64999992"
     inkscape:cx="428.099582"
     inkscape:cy="556.757978"
     inkscape:window-width="637"
     inkscape:window-height="501"
     inkscape:window-x="0"
     inkscape:window-y="0"
     showborder="false" />
  <defs
     id="defs561">
    <linearGradient
       id="linearGradient711">
      <stop
         style="stop-color:#ffffff;stop-opacity:1;"
         offset="0.00000000"
         id="stop712" />
      <stop
         style="stop-color:#868686;stop-opacity:1;"
         offset="1.00000000"
         id="stop713" />
    </linearGradient>
    <linearGradient
       id="linearGradient607">
      <stop
         style="stop-color:#cfcfcf;stop-opacity:1;"
         offset="0.000000"
         id="stop608" />
      <stop
         style="stop-color:#efefef;stop-opacity:1;"
         offset="1.000000"
         id="stop609" />
    </linearGradient>
    <linearGradient
       id="linearGradient565">
      <stop
         style="stop-color:#9d9d9f;stop-opacity:1;"
         offset="0.000000"
         id="stop566" />
      <stop
         style="stop-color:#e5e5e5;stop-opacity:1;"
         offset="1.000000"
         id="stop567" />
    </linearGradient>
    <radialGradient
       id="radialGradient568"
       xlink:href="#linearGradient711"
       cx="0.69677418"
       cy="0.30366492"
       r="0.87194777"
       fx="0.69677418"
       fy="0.30366492"
       spreadMethod="reflect" />
    <linearGradient
       id="linearGradient569"
       xlink:href="#linearGradient565"
       y2="-0.03731298"
       x2="0.72092992"
       y1="0.99253702"
       x1="-0.08527008"
       spreadMethod="pad"
       gradientUnits="objectBoundingBox" />
    <linearGradient
       id="linearGradient580"
       xlink:href="#linearGradient565"
       y2="0.00000002"
       x2="-0.04651194"
       y1="0.99253708"
       x1="-0.00775294"
       spreadMethod="pad"
       gradientUnits="objectBoundingBox" />
    <linearGradient
       xlink:href="#linearGradient565"
       id="linearGradient576" />
    <linearGradient
       xlink:href="#linearGradient607"
       id="linearGradient610"
       x1="0.11764701"
       y1="0.86885244"
       x2="0.78280514"
       y2="0.12295082"
       gradientUnits="objectBoundingBox"
       spreadMethod="pad" />
    <linearGradient
       xlink:href="#linearGradient565"
       id="linearGradient611"
       x1="0.10837435"
       y1="0.94531250"
       x2="0.76847297"
       y2="0.28125000"
       gradientUnits="objectBoundingBox"
       spreadMethod="pad" />
    <linearGradient
       xlink:href="#linearGradient607"
       id="linearGradient613"
       x1="0.23529346"
       y1="0.85156250"
       x2="0.82805431"
       y2="0.12499999"
       gradientUnits="objectBoundingBox"
       spreadMethod="pad" />
    <linearGradient
       xlink:href="#linearGradient565"
       id="linearGradient615"
       x1="0.10731713"
       y1="0.82031238"
       x2="0.87804890"
       y2="0.07812499"
       gradientUnits="objectBoundingBox"
       spreadMethod="pad" />
    <linearGradient
       xlink:href="#linearGradient607"
       id="linearGradient620" />
  </defs>

<!-- Inkscape does not yet support svg:use of an object in defs, therefore we define the key graphics here (on the canvas at 0,0) -->
<!-- They will be overlaid by the background rectangle of the first section -->

<!-- mouse images -->

  <g
     id="left-click">
    <path
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       d="M 3.6677089 0.69866497 C 2.5111219 0.70247797 0.60176688 0.87400498 0.48616554 2.6404201 C 0.36648452 4.20794 0.58434883 5.5470015 1.1224739 6.7127964 C 1.6478125 7.8945497 2.3280327 8.770865 3.7101306 8.791406 C 3.7261892 8.791406 3.7366738 8.791641 3.7525494 8.791406 C 5.1346474 8.770865 5.8148662 7.8945497 6.3402062 6.7127964 C 6.8783313 5.5470015 7.0961985 4.20794 6.9765161 2.6404201 C 6.8609133 0.87400498 4.9515568 0.70247797 3.7949711 0.69866497 C 3.7582543 0.69854407 3.702741 0.69866497 3.6677089 0.69866497 z "
       id="path742"
       transform="matrix(0.886947,0.000000,0.000000,0.886947,0.279045,1.170720)" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.137792;"
       d="M 4.9596784 0.75757138 L 4.9596784 4.5604601 "
       id="path741"
       transform="matrix(0.886947,0.000000,0.000000,0.886947,0.279045,1.170720)" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 2.5836552 0.75683638 C 1.5807894 0.90294429 0.56647766 1.3378565 0.48232843 2.6236796 C 0.42599755 3.3614571 0.43206257 3.9104527 0.52347935 4.5527658 L 2.5836552 4.5527658 L 2.5836552 0.75683638 z "
       id="path740"
       transform="matrix(0.886947,0.000000,0.000000,0.886947,0.279045,1.170720)" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.137792;"
       d="M 2.5571164 0.75757138 L 2.5571164 4.5604601 "
       id="path739"
       transform="matrix(0.886947,0.000000,0.000000,0.886947,0.279045,1.170720)" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.137792;"
       d="M 0.52620977 4.5687418 L 6.9386881 4.5687418 "
       id="path738"
       transform="matrix(0.886947,0.000000,0.000000,0.886947,0.279045,1.170720)" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="0.44536325"
       y="0.10000575"
       id="text743"
       sodipodi:linespacing="100%"
       transform="matrix(1.288158,0.000000,0.000000,1.288158,0.279045,1.170720)"><tspan
         x="0.44536325"
         y="0.10000575"
         sodipodi:role="line"
         id="tspan748">click</tspan></text>
  </g>

  <g
     id="left-drag">
    <path
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       d="M 3.5152508 1.7903988 C 2.4894187 1.7937807 0.79592268 1.9459161 0.69338968 3.5126327 C 0.58723868 4.9029398 0.78047267 6.0906163 1.2577617 7.1246146 C 1.7237087 8.1727672 2.3270277 8.9500124 3.5528758 8.9682312 C 3.5671198 8.9682312 3.5764178 8.9684396 3.5904988 8.9682312 C 4.8163468 8.9500124 5.4196648 8.1727672 5.8856138 7.1246146 C 6.3629028 6.0906163 6.5561389 4.9029398 6.4499868 3.5126327 C 6.3474538 1.9459161 4.6539558 1.7937807 3.6281258 1.7903988 C 3.5955598 1.7902916 3.5463218 1.7903988 3.5152508 1.7903988 z "
       id="path737" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 4.6611588 1.8426457 L 4.6611588 5.2156064 "
       id="path736" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 2.5537517 1.8419938 C 1.6642627 1.9715837 0.76462168 2.3573278 0.68998668 3.4977848 C 0.64002368 4.1521543 0.64540268 4.6390843 0.72648468 5.208782 L 2.5537517 5.208782 L 2.5537517 1.8419938 z "
       id="path735" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 2.5302137 1.8426457 L 2.5302137 5.2156064 "
       id="path734" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 0.72890668 5.2229518 L 6.4164358 5.2229518 "
       id="path733" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 0.080380675 -0.052261417 C 0.47244268 0.40082723 0.75144168 0.87580904 0.83667068 1.4434734 C 1.1760427 1.3485894 1.5154137 1.2537053 1.8547857 1.1588214 C 1.7652587 0.61661809 1.6033797 0.069641022 1.2128567 -0.3818558 C 0.96709368 -0.03094675 0.67231868 0.050643061 0.080380675 -0.052261417 z "
       id="path732" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 0.20099768 1.5517409 L 2.4552837 0.94770692 L 1.5191647 1.9852224 L 0.20099768 1.5517409 z "
       id="path731" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="1.92700259"
       y="1.00883842"
       id="text750"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="1.92700255"
         y="1.00883842"
         sodipodi:role="line"
         id="tspan751">drag</tspan></text>
  </g>

  <g
     id="mid-click">
    <path
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       d="M 3.5020868 1.7911048 C 2.4762557 1.7944862 0.78275968 1.9466216 0.68022768 3.5133391 C 0.57407668 4.9036459 0.76731068 6.0913227 1.2445987 7.125321 C 1.7105457 8.1734737 2.3138647 8.9507193 3.5397118 8.9689372 C 3.5539558 8.9689372 3.5632548 8.9691456 3.5773358 8.9689372 C 4.8031828 8.9507193 5.4065018 8.1734737 5.8724498 7.125321 C 6.3497388 6.0913227 6.5429749 4.9036459 6.4368238 3.5133391 C 6.3342898 1.9466216 4.6407908 1.7944862 3.6149618 1.7911048 C 3.5823958 1.7909978 3.5331588 1.7911048 3.5020868 1.7911048 z "
       id="path753" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 0.71574468 5.2236579 L 6.4032718 5.2236579 "
       id="path757" />
    <text
       xml:space="preserve"
       style="font-size:1.3;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="1.24093144"
       y="1.00938547"
       id="text765"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="1.24093139"
         y="1.00938547"
         sodipodi:role="line"
         id="tspan766">click</tspan></text>
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 2.4989727 1.8559797 L 2.4989727 5.265219 L 4.6627718 5.265219 L 4.6627718 1.8559797 C 3.9666658 1.7238863 3.2453998 1.7238863 2.4989727 1.8559797 z "
       id="path772"
       sodipodi:nodetypes="ccccc" />
  </g>

  <g
     id="mid-drag">
    <path
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       d="M 3.4834688 1.7802168 C 2.4576367 1.7835982 0.76414068 1.9357336 0.66160768 3.5024511 C 0.55545668 4.8927578 0.74869168 6.0804346 1.2259797 7.1144329 C 1.6919267 8.1625855 2.2952467 8.9398302 3.5210948 8.958049 C 3.5353388 8.958049 3.5446368 8.9582575 3.5587168 8.958049 C 4.7845648 8.9398302 5.3878828 8.1625855 5.8538318 7.1144329 C 6.3311198 6.0804346 6.5243569 4.8927578 6.4182048 3.5024511 C 6.3156718 1.9357336 4.6221738 1.7835982 3.5963428 1.7802168 C 3.5637768 1.7801099 3.5145398 1.7802168 3.4834688 1.7802168 z "
       id="path758" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 0.69712568 5.2127698 L 6.3846538 5.2127698 "
       id="path762" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 1.7972947 -0.37695764 C 2.1893557 0.076131434 2.4683557 0.5511128 2.5535847 1.1187771 C 2.8929557 1.023894 3.2323278 0.92900945 3.5716998 0.83412501 C 3.4821728 0.29192246 3.3202938 -0.25505537 2.9297708 -0.70655104 C 2.6840067 -0.35564253 2.3892317 -0.27405316 1.7972947 -0.37695764 z "
       id="path763" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 1.9179107 1.2270443 L 4.1721978 0.6230113 L 3.2360788 1.6605262 L 1.9179107 1.2270443 z "
       id="path764" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="3.27937047"
       y="0.98140591"
       id="text768"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="3.27937055"
         y="0.98140591"
         sodipodi:role="line"
         id="tspan769">drag</tspan></text>
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 2.4992677 1.8450923 L 2.4992677 5.254331 L 4.6630658 5.254331 L 4.6630658 1.8450923 C 3.9669598 1.7129981 3.2456948 1.7129981 2.4992677 1.8450923 z "
       id="path773"
       sodipodi:nodetypes="ccccc" />
  </g>

  <g
     id="right-click">
    <path
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       d="M 3.5470928 1.7706068 C 2.5212607 1.7739882 0.82776368 1.9261236 0.72523168 3.4928414 C 0.61908168 4.8831481 0.81231568 6.0708248 1.2896037 7.1048231 C 1.7555517 8.1529757 2.3588707 8.9302211 3.5847188 8.948439 C 3.5989618 8.948439 3.6082608 8.9486483 3.6223418 8.948439 C 4.8481898 8.9302211 5.4515078 8.1529757 5.9174568 7.1048231 C 6.3947448 6.0708248 6.5879819 4.8831481 6.4818299 3.4928414 C 6.3792958 1.9261236 4.6857978 1.7739882 3.6599678 1.7706068 C 3.6274018 1.7705 3.5781648 1.7706068 3.5470928 1.7706068 z "
       id="path774" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 0.76074868 5.2031601 L 6.4482788 5.2031601 "
       id="path775" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="2.13629596"
       y="0.99347234"
       id="text780"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="2.13629603"
         y="0.99347234"
         sodipodi:role="line"
         id="tspan813">click</tspan></text>
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 4.5998098 1.8222014 C 5.4892978 1.9517915 6.3889388 2.3375356 6.4635749 3.4779927 C 6.5135369 4.132363 6.5081579 4.619292 6.4270768 5.1889904 L 4.5998098 5.1889904 L 4.5998098 1.8222014 z "
       id="path788" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 2.5620557 1.8228546 L 2.5620557 5.1958163 "
       id="path789" />
  </g>

  <g
     id="right-drag">
    <path
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       d="M 3.5538008 1.7504743 C 2.5279697 1.7538557 0.83447268 1.9059911 0.73193968 3.4727085 C 0.62578868 4.8630153 0.81902367 6.0506921 1.2963117 7.0846904 C 1.7622587 8.1328429 2.3655787 8.9100883 3.5914268 8.9283061 C 3.6056708 8.9283061 3.6149688 8.9285155 3.6290498 8.9283061 C 4.8548968 8.9100883 5.4582158 8.1328429 5.9241638 7.0846904 C 6.4014528 6.0506921 6.5946889 4.8630153 6.4885379 3.4727085 C 6.3860038 1.9059911 4.6925058 1.7538557 3.6666758 1.7504743 C 3.6341098 1.7503673 3.5848728 1.7504743 3.5538008 1.7504743 z "
       id="path776" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 0.76745768 5.1830272 L 6.4549858 5.1830272 "
       id="path777" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 4.2209118 -0.40670025 C 4.6129738 0.046388908 4.8919728 0.52137027 4.9772018 1.0890346 C 5.3165738 0.99415146 5.6559448 0.89926693 5.9953168 0.80438248 C 5.9057898 0.26217992 5.7439108 -0.2847979 5.3533878 -0.73629357 C 5.1076248 -0.38538505 4.8128498 -0.30379568 4.2209118 -0.40670025 z "
       id="path778" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 4.3415288 1.1973017 L 6.5958159 0.59326877 L 5.6596958 1.6307837 L 4.3415288 1.1973017 z "
       id="path779" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="0.49732296"
       y="0.95831662"
       id="text783"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="0.49732295"
         y="0.95831662"
         sodipodi:role="line"
         id="tspan784">drag</tspan></text>
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:1pt;"
       d="M 4.6054238 1.8020689 C 5.4949128 1.9316589 6.3945528 2.317403 6.4691899 3.4578599 C 6.5191509 4.1122301 6.5137719 4.5991592 6.4326908 5.1688576 L 4.6054238 5.1688576 L 4.6054238 1.8020689 z "
       id="path790" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 2.5676697 1.802722 L 2.5676697 5.1756835 "
       id="path791" />
  </g>
  <g
     id="wheel">
    <path
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       d="M 3.5370048 1.7303644 C 2.5111727 1.7337458 0.81767667 1.8858811 0.71514468 3.4525986 C 0.60899368 4.8429053 0.80222768 6.0305822 1.2795157 7.0645805 C 1.7454637 8.112733 2.3487827 8.8899785 3.5746308 8.9081964 C 3.5888738 8.9081964 3.5981728 8.9084057 3.6122538 8.9081964 C 4.8381018 8.8899785 5.4414198 8.112733 5.9073688 7.0645805 C 6.3846568 6.0305822 6.5778939 4.8429053 6.4717419 3.4525986 C 6.3692078 1.8858811 4.6757098 1.7337458 3.6498798 1.7303644 C 3.6173138 1.7302575 3.5680768 1.7303644 3.5370048 1.7303644 z "
       id="path792" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 0.75066068 5.1629174 L 2.6033227 5.1629174 "
       id="path793"
       sodipodi:nodetypes="cc" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="0.97063343"
       y="0.96223223"
       id="text794"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="0.97063345"
         y="0.96223223"
         sodipodi:role="line"
         id="tspan795">wheel</tspan></text>
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 6.4381888 5.1629174 L 4.5855278 5.1629174 "
       id="path799"
       sodipodi:nodetypes="cc" />
    <rect
       style="font-size:12;fill:url(#radialGradient568);fill-rule:evenodd;stroke-width:1pt;"
       id="rect801"
       width="1.10310698"
       height="2.92336941"
       x="3.06589717"
       y="2.08157873" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 2.0980692 L 4.1477788 2.0980692 "
       id="path802" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 2.1870294 L 4.1477788 2.1870294 "
       id="path803" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 2.3115737 L 4.1477788 2.3115737 "
       id="path804" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 2.5428703 L 4.1477788 2.5428703 "
       id="path805" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 2.9165032 L 4.1477788 2.9165032 "
       id="path806" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 3.5214326 L 4.1477788 3.5214326 "
       id="path807" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 4.9892801 L 4.1477788 4.9892801 "
       id="path808" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 4.9003199 L 4.1477788 4.9003199 "
       id="path809" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 4.7757756 L 4.1477788 4.7757756 "
       id="path810" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 4.544479 L 4.1477788 4.544479 "
       id="path811" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.064408;"
       d="M 3.0713508 4.1708461 L 4.1477788 4.1708461 "
       id="path812" />
  </g>


<!-- key images -->

  <g
     id="shift">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke:none;stroke-width:0.0625pt;"
       id="rect682"
       width="14.46854401"
       height="6.57892704"
       x="0.03756316"
       y="0.07391790"
       ry="0.68839085" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke:none;stroke-width:0.15625;"
       id="rect683"
       width="12.71428394"
       height="5.05001116"
       x="0.84218349"
       y="0.77243602"
       ry="0.38310501" />
    <text
       style="fill:black;stroke:none;font-family:Bitstream Vera Sans;font-style:italic;font-weight:normal;font-size:4;fill-opacity:1;stroke-opacity:1;stroke-width:1pt;stroke-linejoin:miter;stroke-linecap:butt;text-anchor:start;writing-mode:lr;"
       x="1.37996908"
       y="4.35733509"
       id="text685"
       sodipodi:linespacing="100%"><tspan
         x="1.37996912"
         y="4.35733509"
         sodipodi:role="line"
         id="tspan692">Shift</tspan></text>
  </g>
  <g
     id="ctrl">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke:none;stroke-width:0.0625pt;"
       id="rect695"
       width="11.38750172"
       height="6.57892704"
       x="0"
       y="0"
       ry="0.68839085" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke:none;stroke-width:0.15625;"
       id="rect696"
       width="9.74373341"
       height="5.05001116"
       x="0.77"
       y="0.77"
       ry="0.38310501" />
    <text
       style="fill:black;stroke:none;font-family:Bitstream Vera Sans;font-style:italic;font-weight:normal;font-size:4;fill-opacity:1;stroke-opacity:1;stroke-width:1pt;stroke-linejoin:miter;stroke-linecap:butt;text-anchor:start;writing-mode:lr;"
       x="1.3"
       y="4.35733509"
       id="text697"
       sodipodi:linespacing="100%"><tspan
         x="1.3"
         y="4.35733509"
         sodipodi:role="line"
         id="tspan698">Ctrl</tspan></text>
  </g>
  <g
     id="alt">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke:none;stroke-width:0.0625pt;"
       id="rect703"
       width="9.67487087"
       height="6.57892704"
       x="0"
       y="0"
       ry="0.68839085" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke:none;stroke-width:0.15625;"
       id="rect704"
       width="7.97585612"
       height="5.05001116"
       x="0.77"
       y="0.77"
       ry="0.38310501" />
    <text
       style="fill:black;stroke:none;font-family:Bitstream Vera Sans;font-style:italic;font-weight:normal;font-size:4;fill-opacity:1;stroke-opacity:1;stroke-width:1pt;stroke-linejoin:miter;stroke-linecap:butt;text-anchor:start;writing-mode:lr;"
       x="1.3"
       y="4.35733509"
       id="text705"
       sodipodi:linespacing="100%"><tspan
         x="1.3"
         y="4.35733509"
         sodipodi:role="line"
         id="tspan706">Alt</tspan></text>
  </g>

  <g
     id="left">
    <text
       style="fill:black;stroke:none;font-family:Bitstream Vera Sans;font-style:italic;font-weight:normal;font-size:4;fill-opacity:1;stroke-opacity:1;stroke-width:1pt;stroke-linejoin:miter;stroke-linecap:butt;text-anchor:start;writing-mode:lr;letter-spacing:-0.3;"
       x="1.3"
       y="4.35733509"
       sodipodi:linespacing="100%"><tspan
         x="1.3"
         y="4.35733509"
         sodipodi:role="line"
         >Left</tspan></text>
  </g>

  <g
     id="right">
    <text
       style="fill:black;stroke:none;font-family:Bitstream Vera Sans;font-style:italic;font-weight:normal;font-size:4;fill-opacity:1;stroke-opacity:1;stroke-width:1pt;stroke-linejoin:miter;stroke-linecap:butt;text-anchor:start;writing-mode:lr;letter-spacing:-0.3;"
       x="1.3"
       y="4.35733509"
       sodipodi:linespacing="100%"><tspan
         x="1.3"
         y="4.35733509"
         sodipodi:role="line"
         >Right</tspan></text>
  </g>

  <g
     id="letterkey">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke:none;stroke-width:0.0625pt;"
       id="rect708"
       width="7.00721359"
       height="6.57892704"
       x="0"
       y="0"
       ry="0.97501397" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke:none;stroke-width:0.15625;"
       id="rect709"
       width="5.07888126"
       height="5.05001116"
       x="0.77"
       y="0.77"
       ry="0.48707163"
       rx="0.35459363" />
  </g>

  <g
     id="misc-wide">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke:none;stroke-width:0.0625pt;"
       width="16.46854401"
       height="6.57892704"
       x="0.0"
       y="0.0"
       ry="0.68839085" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke:none;stroke-width:0.15625;"
       width="14.7"
       height="5.0"
       x="0.77"
       y="0.77"
       ry="0.38310501" />
  </g>

  <g
     id="misc">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke:none;stroke-width:0.0625pt;"
       width="11.4"
       height="6.57892704"
       x="0.0"
       y="0.0"
       ry="0.68839085" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke:none;stroke-width:0.15625;"
       width="9.7"
       height="5.0"
       x="0.77"
       y="0.77"
       ry="0.38310501" />
  </g>

  <g
     id="arrows">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke-width:0.0625pt;"
       id="rect708"
       width="3.50360680"
       height="3.28946352"
       x="3.72818561"
       y="0.09945580"
       ry="0.48750699" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke-width:0.15625;"
       id="rect709"
       width="2.53944063"
       height="2.52500558"
       x="4.19200130"
       y="0.44871032"
       ry="0.24353582"
       rx="0.17729682" />
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke-width:0.0625pt;"
       id="rect787"
       width="3.50360680"
       height="3.28946352"
       x="3.72818561"
       y="3.64276290"
       ry="0.48750699" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke-width:0.15625;"
       id="rect788"
       width="2.53944063"
       height="2.52500558"
       x="4.19200130"
       y="3.99201751"
       ry="0.24353582"
       rx="0.17729682" />
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke-width:0.0625pt;"
       id="rect789"
       width="3.50360680"
       height="3.28946352"
       x="-0.00256788"
       y="3.64276290"
       ry="0.48750699" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke-width:0.15625;"
       id="rect790"
       width="2.53944063"
       height="2.52500558"
       x="0.46125068"
       y="3.99201751"
       ry="0.24353582"
       rx="0.17729682" />
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke-width:0.0625pt;"
       id="rect791"
       width="3.50360680"
       height="3.28946352"
       x="7.45893283"
       y="3.64276290"
       ry="0.48750699" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke-width:0.15625;"
       id="rect792"
       width="2.53944063"
       height="2.52500558"
       x="7.92275138"
       y="3.99201751"
       ry="0.24353582"
       rx="0.17729682" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="2.21508991"
       y="6.47878742"
       id="text796"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="2.21508980"
         y="6.47878742"
         sodipodi:role="line"
         id="tspan797">arrows</tspan></text>
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 5.1322313 0.90289456 L 5.1322313 2.6190467 "
       id="path801"
       sodipodi:nodetypes="cc" />
    <path
       style="fill:#000000;fill-rule:evenodd;stroke:none;stroke-opacity:1;stroke-width:0;stroke-linejoin:miter;stroke-linecap:butt;fill-opacity:1;stroke-dasharray:none;"
       d="M 4.6182793 1.3212845 L 5.1418233 0.81871946 L 5.6541543 1.3212845 L 4.6182793 1.3212845 z "
       id="path813"
       sodipodi:nodetypes="cccc" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 5.1322313 6.0781819 L 5.1322313 4.3620297 "
       id="path814"
       sodipodi:nodetypes="cc" />
    <path
       style="fill:#000000;fill-rule:evenodd;stroke:none;stroke-opacity:1;stroke-width:0;stroke-linejoin:miter;stroke-linecap:butt;fill-opacity:1;stroke-dasharray:none;"
       d="M 4.6182793 5.6597919 L 5.1418233 6.162357 L 5.6541543 5.6597919 L 4.6182793 5.6597919 z "
       id="path815"
       sodipodi:nodetypes="cccc" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 9.868405 5.2661777 L 8.1522594 5.2661777 "
       id="path816"
       sodipodi:nodetypes="cc" />
    <path
       style="fill:#000000;fill-rule:evenodd;stroke:none;stroke-opacity:1;stroke-width:0;stroke-linejoin:miter;stroke-linecap:butt;fill-opacity:1;stroke-dasharray:none;"
       d="M 9.4500205 5.7801297 L 9.952579 5.2565857 L 9.4500205 4.7442547 L 9.4500205 5.7801297 z "
       id="path817"
       sodipodi:nodetypes="cccc" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.122214;"
       d="M 0.76312022 5.2661777 L 2.4792643 5.2661777 "
       id="path818"
       sodipodi:nodetypes="cc" />
    <path
       style="fill:#000000;fill-rule:evenodd;stroke:none;stroke-opacity:1;stroke-width:0;stroke-linejoin:miter;stroke-linecap:butt;fill-opacity:1;stroke-dasharray:none;"
       d="M 1.1815105 5.7801297 L 0.67894514 5.2565857 L 1.1815105 4.7442547 L 1.1815105 5.7801297 z "
       id="path819"
       sodipodi:nodetypes="cccc" />
  </g>

  <g
     id="up">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke:none;stroke-width:0.0625pt;"
       id="rect800"
       width="7.00721359"
       height="6.57892704"
       x="-0.00741097"
       y="0.11458590"
       ry="0.97501397" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke:none;stroke-width:0.15625;"
       id="rect802"
       width="5.07888126"
       height="5.05001116"
       x="0.92021832"
       y="0.81310272"
       ry="0.48707163"
       rx="0.35459363" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.244428;"
       d="M 2.8349462 1.7275401 L 2.8349462 5.1598442 "
       id="path825"
       sodipodi:nodetypes="cc" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:0;"
       d="M 1.8070423 2.5643198 L 2.8541302 1.5591899 L 3.8787922 2.5643198 L 1.8070423 2.5643198 z "
       id="path826"
       sodipodi:nodetypes="cccc" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="1.82973492"
       y="6.29683936"
       id="text827"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="1.82973492"
         y="6.29683924"
         sodipodi:role="line"
         id="tspan828">up</tspan></text>
  </g>
  <g
     id="down">
    <rect
       style="font-size:12;fill:url(#linearGradient615);fill-rule:evenodd;stroke-width:0.0625pt;"
       id="rect839"
       width="7.00721359"
       height="6.57892704"
       x="-0.00740963"
       y="0.11458590"
       ry="0.97501397" />
    <rect
       style="font-size:12;fill:url(#linearGradient613);fill-rule:evenodd;stroke-width:0.15625;"
       id="rect840"
       width="5.07888126"
       height="5.05001116"
       x="0.92021960"
       y="0.81310272"
       ry="0.48707163"
       rx="0.35459363" />
    <path
       style="font-size:12;fill:none;fill-opacity:0.75;fill-rule:evenodd;stroke:#000000;stroke-width:0.244428;"
       d="M 2.8349477 4.9915303 L 2.8349477 1.5592262 "
       id="path841"
       sodipodi:nodetypes="cc" />
    <path
       style="font-size:12;fill-rule:evenodd;stroke-width:0;"
       d="M 1.8070437 4.1547506 L 2.8541317 5.1598805 L 3.8787938 4.1547506 L 1.8070437 4.1547506 z "
       id="path842"
       sodipodi:nodetypes="cccc" />
    <text
       xml:space="preserve"
       style="font-size:1.2;font-weight:normal;stroke-width:1pt;font-family:Bitstream Vera Sans;"
       x="1.04129975"
       y="6.29683924"
       id="text843"
       sodipodi:linespacing="100%"
       transform="scale(1.288158,1.288158)"><tspan
         x="1.04129970"
         y="6.29683924"
         sodipodi:role="line"
         id="tspan844">down</tspan></text>
  </g>


<xsl:apply-templates/>
</svg>
</xsl:template>

<xsl:template match="k:root/text() | k:column/text() | root/p"/>

<xsl:template match="k:column">
<xsl:variable name="y" select="
 count(preceding::k:section)*$space-section + 
 count(preceding::k:group)*$space-group + 
 count(preceding::k:title)*$space-title + 
 count(preceding::k:keys)*$space-keys + 
 count(preceding::k:mouse)*$space-mouse + 
 count(preceding::k:note)*$space-note"/>
<xsl:variable name="x" select="count(preceding::k:column)*$section-width"/>
 <g transform="translate({$x},{-$y})">
  <xsl:apply-templates/>
 </g>
</xsl:template>

<xsl:template match="k:section">
<xsl:variable name="y" select="
 count(preceding::k:section)*$space-section + 
 count(preceding::k:group)*$space-group + 
 count(preceding::k:title)*$space-title + 
 count(preceding::k:keys)*$space-keys + 
 count(preceding::k:mouse)*$space-mouse + 
 count(preceding::k:note)*$space-note"/>
<xsl:variable name="h" select="
 $space-section + 
 count(descendant::k:group)*$space-group + 
 count(descendant::k:title)*$space-title + 
 count(descendant::k:keys)*$space-keys + 
 count(descendant::k:mouse)*$space-mouse + 
 count(descendant::k:note)*$space-note"/>
  <rect
     style="fill:#{@color};fill-rule:evenodd;stroke:#000000;stroke-width:2.0"
     width="{$section-width}"
     height="{$h}"
     x="0"
     y="{$y}"/>
  <text
     xml:space="preserve"
     style="{$style-section}"
     x="{$section-hskip + 1*$w-key}"
     y="{$y + $skip-section-title}"
     id="sect{count(preceding-sibling::k:section) + 1}"
     ><tspan
       x="{$section-hskip + 1*$w-key}"
       y="{$y + $skip-section-title}"
       sodipodi:role="line"
       id="sect-tspan{count(preceding-sibling::k:section) + 1}"
       ><xsl:value-of select="@title"/></tspan></text>
<xsl:apply-templates/>
</xsl:template>

<xsl:template match="k:title">
<xsl:variable name="y" select="
 count(preceding::k:section) * $space-section + 
 count(preceding::k:group)*$space-group + 
 count(preceding::k:title)*$space-title + 
 count(preceding::k:keys)*$space-keys + 
 count(preceding::k:mouse)*$space-mouse + 
 count(preceding::k:note)*$space-note +
 $skip-section-content +
 $skip-group-content +
 $skip-title-content"/>

  <text
     xml:space="preserve"
     style="{$style-title}"
     x="{$section-hskip + 1*$w-key}"
     y="{$y}"
     id="title{count(preceding::k:title)+1}"
     ><tspan
       x="{$section-hskip + 1*$w-key}"
       y="{$y}"
       sodipodi:role="line"
       id="title-tspan{count(preceding::k:title)+1}"><xsl:value-of select="text()"/></tspan></text>

</xsl:template>

<xsl:template match="k:note">
<xsl:variable name="y" select="
 count(preceding::k:section) * $space-section + 
 count(preceding::k:group)*$space-group + 
 count(preceding::k:title)*$space-title + 
 count(preceding::k:keys)*$space-keys + 
 count(preceding::k:mouse)*$space-mouse + 
 count(preceding::k:note)*$space-note +
 $skip-section-content +
 $skip-group-content +
 $skip-note-content"/>

  <text
     xml:space="preserve"
     style="{$style-note}"
     x="{$section-hskip + $note-hskip}"
     y="{$y}"
     id="note{count(preceding::k:note)+1}"
     ><tspan
       x="{$section-hskip + $note-hskip}"
       y="{$y}"
       sodipodi:role="line"
       id="note-tspan{count(preceding::k:note)+1}"><xsl:value-of select="text()"/></tspan></text>

</xsl:template>


<xsl:template match="k:keys">
<xsl:variable name="y" select="
 count(preceding::k:section) * $space-section + 
 count(preceding::k:group)*$space-group + 
 count(preceding::k:title)*$space-title + 
 count(preceding::k:keys)*$space-keys + 
 count(preceding::k:mouse)*$space-mouse + 
 count(preceding::k:note)*$space-note +
 $skip-section-content +
 $skip-group-content +
 $skip-keys-content"/>
<xsl:apply-templates select="k:key | k:action">
<xsl:with-param name="y" select="$y"/>
</xsl:apply-templates>
</xsl:template>

<xsl:template match="k:mouse">
<xsl:variable name="y" select="
 count(preceding::k:section) * $space-section + 
 count(preceding::k:group)*$space-group + 
 count(preceding::k:title)*$space-title + 
 count(preceding::k:keys)*$space-keys + 
 count(preceding::k:mouse)*$space-mouse + 
 count(preceding::k:note)*$space-note +
 $skip-section-content +
 $skip-group-content +
 $skip-mouse-content"/>
<xsl:apply-templates select="k:key | k:action">
<xsl:with-param name="y" select="$y"/>
</xsl:apply-templates>
</xsl:template>

<xsl:template match="k:action">
<xsl:param name="y"/>
<xsl:variable name="x" select="2*$w-key + $section-hskip + $action-hskip"/> <!--max two keys-->
  <text
     xml:space="preserve"
     style="{$style-action}"
     x="{$x}"
     y="{$y + $skip-keys-action}"
     id="action{count(preceding::k:action)+1}"
     ><tspan
       x="{$x}"
       y="{$y + $skip-keys-action}"
       sodipodi:role="line"
       id="action-tspan{count(preceding::k:action)+1}"
       ><xsl:value-of select="text()"/></tspan></text>
</xsl:template>

<xsl:template match="k:key">
<xsl:param name="y"/>
<xsl:variable name="x" select="(1 - count(following-sibling::k:key))*$w-key + $section-hskip"/> <!--max two keys-->
<xsl:apply-templates>
<xsl:with-param name="x" select="$x"/>
<xsl:with-param name="y" select="$y"/>
</xsl:apply-templates>
<xsl:if test="following-sibling::k:key/node()">
  <text
     xml:space="preserve"
     style="{$style-action}"
     x="{$x + $w-key - 1}"
     y="{$y + $skip-keys-action}"
     ><tspan
       x="{$x + $w-key - 1}"
       y="{$y + $skip-keys-action}"
       sodipodi:role="line"
       >,</tspan></text>
</xsl:if>
</xsl:template>

<xsl:template match="k:shift | k:ctrl | k:alt | k:left | k:right">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 count(following-sibling::k:shift | self::k:shift)*$w-shift -
 count(following-sibling::k:ctrl | self::k:ctrl)*$w-ctrl -
 count(following-sibling::k:alt | self::k:alt)*$w-alt -
 count(following-sibling::k:left | self::k:left)*$w-left -
 count(following-sibling::k:right | self::k:right)*$w-right -
 count(following-sibling::text())*$w-letterkey -
 count(following-sibling::k:keyf)*$w-letterkey -
 count(following-sibling::k:misc-wide)*$w-misc-wide -
 count(following-sibling::k:misc)*$w-misc -
 count(following-sibling::k:arrows)*$w-arrows -
 count(following-sibling::k:wheel | following-sibling::k:left-click | following-sibling::k:left-drag | following-sibling::k:mid-click | following-sibling::k:mid-drag | following-sibling::k:right-click | following-sibling::k:right-drag)*$w-mouse
"/>
<use xlink:href="#{name()}"
transform="translate({$xx},{$y})"/>
</xsl:template>

<xsl:template match="k:key/text()">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 $w-letterkey"/>
<use xlink:href="#letterkey"
transform="translate({$xx},{$y})"/>
    <text
       xml:space="preserve"
       style="{$style-letterkey}"
       x="{1.7 + $xx}"
       y="{4.66851145 + $y}"
       ><tspan
         x="{1.7 + $xx}"
         y="{4.66851145 + $y}"
         sodipodi:role="line"
         ><xsl:value-of select="."/></tspan></text>
</xsl:template>

<xsl:template match="k:keyf">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 $w-letterkey"/>
<use xlink:href="#letterkey"
transform="translate({$xx},{$y})"/>
    <text
       xml:space="preserve"
       style="{$style-keyf}"
       x="{0.9 + $xx}"
       y="{3.5 + $y}"
       ><tspan
         x="{0.9 + $xx}"
         y="{3.5 + $y}"
         sodipodi:role="line"
         ><xsl:value-of select="@f"/></tspan></text>
</xsl:template>

<xsl:template match="k:misc-wide">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 $w-misc-wide"/>
<use xlink:href="#misc-wide"
transform="translate({$xx},{$y})"/>
    <text
       xml:space="preserve"
       style="{$style-keymisc}"
       x="{1.1 + $xx}"
       y="{3.7 + $y}"
       ><tspan
         x="{1.1 + $xx}"
         y="{3.7 + $y}"
         sodipodi:role="line"
         ><xsl:value-of select="@f"/></tspan></text>
</xsl:template>

<xsl:template match="k:misc">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 $w-misc"/>
<use xlink:href="#misc"
transform="translate({$xx},{$y})"/>
    <text
       xml:space="preserve"
       style="{$style-keymisc}"
       x="{1.1 + $xx}"
       y="{3.7 + $y}"
       ><tspan
         x="{1.1 + $xx}"
         y="{3.7 + $y}"
         sodipodi:role="line"
         ><xsl:value-of select="@f"/></tspan></text>
</xsl:template>

<xsl:template match="k:arrows">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 $w-arrows"/>
<use xlink:href="#arrows"
transform="translate({$xx},{$y})"/>
</xsl:template>

<xsl:template match="k:up | k:down">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 $w-letterkey"/>
<use xlink:href="#{name()}"
transform="translate({$xx},{$y})"/>
</xsl:template>

<xsl:template match="k:wheel | k:left-click | k:left-drag | k:mid-click | k:mid-drag | k:right-click | k:right-drag">
<xsl:param name="x"/>
<xsl:param name="y"/>
<xsl:variable name="xx" select="
 $x +
 $w-key - 
 $w-mouse -
 count(following-sibling::k:misc-wide)*($w-misc-wide + 1)"/>
<use xlink:href="#{name()}"
transform="translate({$xx},{$y})"/>
</xsl:template>

</xsl:stylesheet>