#!/bin/bash
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>
# Inkscape Modifications: ~suv <suv-sf@users.sourceforge.net>

get_env_current ()
{
	awk 'BEGIN { for (v in ENVIRON) print v }' | sort -u
}
[ -z "$_env_orig" ] && export _env_orig="$(get_env_current)"

CWD="$(cd "$(dirname "$0")" && pwd)"

source "${CWD}/xdg_setup.sh"

exec "$CWD/bin/inkscape" "$@"
