#ifndef SP_DESKTOP_UNITS_H
#define SP_DESKTOP_UNITS_H

#define POINTS_PER_INCH 72.0
#define INCHES_PER_POINT (1 / POINTS_PER_INCH)
#define CM_PER_INCH 2.54
#define INCHES_PER_CM (1 / CM_PER_INCH)
#define POINTS_PER_CM (POINTS_PER_INCH * INCHES_PER_CM)
#define CM_PER_POINT (1 / POINTS_PER_CM)

#endif

