#define TOOL_BUTTON_SIZE 28

#define AUX_BUTTON_SIZE 20
#define AUX_BETWEEN_BUTTON_GROUPS 5
#define AUX_BETWEEN_SPINBUTTONS 2
#define AUX_FONT_SIZE 8000
#define AUX_SPINBUTTON_WIDTH 57
#define AUX_SPINBUTTON_HEIGHT 22
#define AUX_OPTION_MENU_WIDTH 55
#define AUX_OPTION_MENU_HEIGHT 18
#define AUX_MENU_ITEM_WIDTH 32
#define AUX_MENU_ITEM_HEIGHT 18
