#define TOOL_BUTTON_SIZE 28

#define AUX_BUTTON_SIZE 20
#define AUX_BETWEEN_BUTTON_GROUPS 5
#define AUX_BETWEEN_SPINBUTTONS 2
#define AUX_FONT_SIZE 8000
#define AUX_SPINBUTTON_WIDTH 57
#define AUX_SPINBUTTON_HEIGHT 22
#define AUX_OPTION_MENU_WIDTH 55
#define AUX_OPTION_MENU_HEIGHT 18
#define AUX_MENU_ITEM_WIDTH 32
#define AUX_MENU_ITEM_HEIGHT 18

#define SPIN_STEP 0.1
#define SPIN_PAGE_STEP 5.0

#define STATUS_BAR_FONT_SIZE 10000
#define STATUS_COORD_FONT_SIZE 8500
#define STATUS_ZOOM_FONT_SIZE 7000
#define STATUS_ZOOM_WIDTH 56
#define STATUS_COORD_WIDTH 90
