###########################################################################
#  $Id$
###########################################################################
# Makefile for building with MinGW
###########################################################################

include ../../Makefile.mingw.common



OBJ = \
gnome-canvas-bpath-util.o svg-affine.o svg-color.o svg-length.o \
svg-path.o

all: $(OBJ)


clean:
	$(RM) *.o
	$(RM) *.a
